package com.diabetes.instameal.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.diabetes.instameal.model.Meal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEAL".
*/
public class MealDao extends AbstractDao<Meal, Long> {

    public static final String TABLENAME = "MEAL";

    /**
     * Properties of entity Meal.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PreGlycemia = new Property(1, Integer.class, "preGlycemia", false, "PRE_GLYCEMIA");
        public final static Property PosGlycemia = new Property(2, Integer.class, "posGlycemia", false, "POS_GLYCEMIA");
        public final static Property UnitInsulin = new Property(3, Float.class, "unitInsulin", false, "UNIT_INSULIN");
        public final static Property Date = new Property(4, java.util.Date.class, "date", false, "DATE");
        public final static Property PreExerciseLevel = new Property(5, Integer.class, "preExerciseLevel", false, "PRE_EXERCISE_LEVEL");
        public final static Property Description = new Property(6, String.class, "description", false, "DESCRIPTION");
        public final static Property IdImage = new Property(7, String.class, "idImage", false, "ID_IMAGE");
        public final static Property Type = new Property(8, String.class, "type", false, "TYPE");
    };


    public MealDao(DaoConfig config) {
        super(config);
    }
    
    public MealDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PRE_GLYCEMIA\" INTEGER," + // 1: preGlycemia
                "\"POS_GLYCEMIA\" INTEGER," + // 2: posGlycemia
                "\"UNIT_INSULIN\" REAL," + // 3: unitInsulin
                "\"DATE\" INTEGER," + // 4: date
                "\"PRE_EXERCISE_LEVEL\" INTEGER," + // 5: preExerciseLevel
                "\"DESCRIPTION\" TEXT," + // 6: description
                "\"ID_IMAGE\" TEXT," + // 7: idImage
                "\"TYPE\" TEXT);"); // 8: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEAL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Meal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer preGlycemia = entity.getPreGlycemia();
        if (preGlycemia != null) {
            stmt.bindLong(2, preGlycemia);
        }
 
        Integer posGlycemia = entity.getPosGlycemia();
        if (posGlycemia != null) {
            stmt.bindLong(3, posGlycemia);
        }
 
        Float unitInsulin = entity.getUnitInsulin();
        if (unitInsulin != null) {
            stmt.bindDouble(4, unitInsulin);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(5, date.getTime());
        }
 
        Integer preExerciseLevel = entity.getPreExerciseLevel();
        if (preExerciseLevel != null) {
            stmt.bindLong(6, preExerciseLevel);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(7, description);
        }
 
        String idImage = entity.getIdImage();
        if (idImage != null) {
            stmt.bindString(8, idImage);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(9, type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Meal readEntity(Cursor cursor, int offset) {
        Meal entity = new Meal( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // preGlycemia
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // posGlycemia
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // unitInsulin
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // date
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // preExerciseLevel
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // description
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // idImage
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Meal entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPreGlycemia(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPosGlycemia(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setUnitInsulin(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setPreExerciseLevel(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDescription(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIdImage(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setType(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Meal entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Meal entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
