package com.diabetes.instameal.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MEAL".
 */
public class Meal {

    private Long id;
    private Integer preGlycemia;
    private Integer posGlycemia;
    private Float unitInsulin;
    private java.util.Date date;
    private Integer preExerciseLevel;
    private String description;
    private String idImage;
    private String type;

    public Meal() {
    }

    public Meal(Long id) {
        this.id = id;
    }

    public Meal(Long id, Integer preGlycemia, Integer posGlycemia, Float unitInsulin, java.util.Date date, Integer preExerciseLevel, String description, String idImage, String type) {
        this.id = id;
        this.preGlycemia = preGlycemia;
        this.posGlycemia = posGlycemia;
        this.unitInsulin = unitInsulin;
        this.date = date;
        this.preExerciseLevel = preExerciseLevel;
        this.description = description;
        this.idImage = idImage;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPreGlycemia() {
        return preGlycemia;
    }

    public void setPreGlycemia(Integer preGlycemia) {
        this.preGlycemia = preGlycemia;
    }

    public Integer getPosGlycemia() {
        return posGlycemia;
    }

    public void setPosGlycemia(Integer posGlycemia) {
        this.posGlycemia = posGlycemia;
    }

    public Float getUnitInsulin() {
        return unitInsulin;
    }

    public void setUnitInsulin(Float unitInsulin) {
        this.unitInsulin = unitInsulin;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getPreExerciseLevel() {
        return preExerciseLevel;
    }

    public void setPreExerciseLevel(Integer preExerciseLevel) {
        this.preExerciseLevel = preExerciseLevel;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getIdImage() {
        return idImage;
    }

    public void setIdImage(String idImage) {
        this.idImage = idImage;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
